#========== 服务器 配置信息===========#
#服务器端口映射
server:
  port: 8099
  #服务项目名
  servlet:
    path: /redis

#==========redis 配置信息===========#
spring:
  redis:
    #（单机redis）数据库ip
    host: 127.0.0.1
    #（单机redis）数据库端口
    port: 6397
    #数据库指定索引
    database: 1
    #数据库密码
    password:
    #超时时间
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数，负值表示不限制
        max-active: 1000
        #连接池中最大空闲连接
        max-idle: 10
        #连接池中最小空闲连接
        min-idle: 2
        #连接池最大阻塞等待时间，负值表示不限制
        max-wait: -1

#    cluster:
#      #（cluster集群，不使用则不用开启）在群集中执行命令时要遵循的最大重定向数目。
#      max-redirects: 3
#      #（cluster集群，不使用则不用开启）以逗号分隔的“主机：端口”对列表进行引导。
#      nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
#    sentinel:
#      #（哨兵模式，不使用则不用开启）Redis服务器的名称。
#      master:
#      #（哨兵模式，不使用则不用开启）主机：端口对的逗号分隔列表。
#      nodes=:
#
